-- Databricks notebook source
select *
from corr_cups_nt
limit 10;

-- COMMAND ----------

SELECT
  *
FROM
  temp_suficiencia_unificado_dw
LIMIT
  500;

-- COMMAND ----------

-- muestra de 1.000.000 millón cédulas únicas año 2018
CREATE OR REPLACE TABLE muestra_un_millon_suficiencia_2018 AS
SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, DESC_ACTIVIDAD, NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA
FROM (
  SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, DESC_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
  FROM temp_suficiencia_unificado_dw
  WHERE NUM_ANO = 2018 -- Filtro para NUM_ANO = 2018
    AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
) subquery
WHERE row_num = 1
ORDER BY RAND()
LIMIT 1000000;

SELECT *
FROM muestra_un_millon_suficiencia_2018
limit 10;

-- COMMAND ----------

-- conteo de registros de la muestra
SELECT COUNT(*) AS total_registros
FROM (
    SELECT STR_IDENTIFICACION, STR_TIPO_ID, COUNT(*) AS conteo
    FROM muestra_un_millon_suficiencia_2018
    GROUP BY STR_IDENTIFICACION, STR_TIPO_ID
    --HAVING COUNT(*) > 1;
) subquery;

-- COMMAND ----------

-- Tabla año 2018, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
CREATE OR REPLACE TABLE tabla_muestra_un_millon_suficiencia_2018
AS
SELECT
  TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
  STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA, 
  SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
  COUNT(NT_RULES) AS Frecuencia--
FROM muestra_un_millon_suficiencia_2018
GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA;

SELECT
  *
FROM
  tabla_muestra_un_millon_suficiencia_2018

-- COMMAND ----------

-- muestra de 1.000.000 millón cédulas únicas año 2019
CREATE OR REPLACE TABLE muestra_un_millon_suficiencia_2019 AS
SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
FROM (
  SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
  FROM temp_suficiencia_unificado_dw
  WHERE NUM_ANO = 2019 -- Filtro para NUM_ANO = 2019
    AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
) subquery
WHERE row_num = 1
ORDER BY RAND()
LIMIT 1000000;

SELECT *
FROM muestra_un_millon_suficiencia_2019
limit 10;

-- COMMAND ----------

-- Tabla año 2019, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
CREATE OR REPLACE TABLE tabla_muestra_un_millon_suficiencia_2019
AS
SELECT
  TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
  STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA, 
  SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
  COUNT(NT_RULES) AS Frecuencia
FROM muestra_un_millon_suficiencia_2019
GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA;

SELECT
  *
FROM
  tabla_muestra_un_millon_suficiencia_2019

-- COMMAND ----------

-- muestra de 1.000.000 millón cédulas únicas año 2020
CREATE OR REPLACE TABLE muestra_un_millon_suficiencia_2020 AS
SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
FROM (
  SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
  FROM temp_suficiencia_unificado_dw
  WHERE NUM_ANO = 2020 -- Filtro para NUM_ANO = 2020
    AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
) subquery
WHERE row_num = 1
ORDER BY RAND()
LIMIT 1000000;

SELECT *
FROM muestra_un_millon_suficiencia_2020
limit 10;

-- COMMAND ----------

-- Tabla año 2020, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
CREATE OR REPLACE TABLE tabla_muestra_un_millon_suficiencia_2020
AS
SELECT
  TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
  STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA, 
  SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
  COUNT(NT_RULES) AS Frecuencia
FROM muestra_un_millon_suficiencia_2020
GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA;

SELECT
  *
FROM
  tabla_muestra_un_millon_suficiencia_2020

-- COMMAND ----------

-- muestra de 1.000.000 millón cédulas únicas año 2021
CREATE OR REPLACE TABLE muestra_un_millon_suficiencia_2021 AS
SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
FROM (
  SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
  FROM temp_suficiencia_unificado_dw
  WHERE NUM_ANO = 2021 -- Filtro para NUM_ANO = 2021
    AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
) subquery
WHERE row_num = 1
ORDER BY RAND()
LIMIT 1000000;

SELECT *
FROM muestra_un_millon_suficiencia_2021
limit 10;

-- COMMAND ----------

-- Tabla año 2021, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
CREATE OR REPLACE TABLE tabla_muestra_un_millon_suficiencia_2021
AS
SELECT
  TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
  STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA, 
  SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
  COUNT(NT_RULES) AS Frecuencia
FROM muestra_un_millon_suficiencia_2021
GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA;

SELECT
  *
FROM
  tabla_muestra_un_millon_suficiencia_2021

-- COMMAND ----------

-- muestra de 1.000.000 millón cédulas únicas año 2022
CREATE OR REPLACE TABLE muestra_un_millon_suficiencia_2022 AS
SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD, NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
FROM (
  SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
  FROM temp_suficiencia_unificado_dw
  WHERE NUM_ANO = 2022 -- Filtro para NUM_ANO = 2022
    AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
) subquery
WHERE row_num = 1
ORDER BY RAND()
LIMIT 1000000;

SELECT *
FROM muestra_un_millon_suficiencia_2022
limit 10;

-- COMMAND ----------

-- Tabla año 2022, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
CREATE OR REPLACE TABLE tabla_muestra_un_millon_suficiencia_2022
AS
SELECT
  TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
  STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA, 
  SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
  COUNT(NT_RULES) AS Frecuencia
FROM muestra_un_millon_suficiencia_2022
GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
  DESC_EPS, 
  STR_REGIMEN, 
  STR_COD_ACTIVIDAD,  
  NOMBRE_ACTIVIDAD, 
  DESC_ACTIVIDAD,
  NT_RULES, 
  NT_DENOMINA;

SELECT
  *
FROM
  tabla_muestra_un_millon_suficiencia_2022

-- COMMAND ----------

-- Unir las tablas de la muestra dos millon años 2018_a_2022
CREATE OR REPLACE TABLE muestra_un_millon_eps_sufici_contri_2018_a_2022 AS
SELECT * FROM tabla_muestra_un_millon_suficiencia_2018
UNION 
SELECT * FROM tabla_muestra_un_millon_suficiencia_2019
UNION 
SELECT * FROM tabla_muestra_un_millon_suficiencia_2020
UNION 
SELECT * FROM tabla_muestra_un_millon_suficiencia_2021
UNION 
SELECT * FROM tabla_muestra_un_millon_suficiencia_2022;

-- Select data from the table
SELECT *
FROM muestra_un_millon_eps_sufici_contri_2018_a_2022;
