# Databricks notebook source
# MAGIC %sql
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   corr_cups_nt
# MAGIC LIMIT
# MAGIC   5;

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE corr_cups_nt;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   temp_suficiencia_unificado_transformacion
# MAGIC LIMIT
# MAGIC   10;

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE temp_suficiencia_unificado_transformacion;

# COMMAND ----------

# MAGIC %sql
# MAGIC select
# MAGIC   year(DTM_FECHA_SERV), count(*)
# MAGIC from temp_suficiencia_unificado_transformacion
# MAGIC group by year(DTM_FECHA_SERV);

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2018
# MAGIC CREATE OR REPLACE TABLE muestra_estudio_suficiencia_2018 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2018 -- Filtro para NUM_ANO = 2018 
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C'
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC SELECT *
# MAGIC FROM muestra_estudio_suficiencia_2018
# MAGIC limit 10;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla total Año 2018, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_resultados_suficiencia_2018
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_estudio_suficiencia_2018
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_resultados_suficiencia_2018;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2019
# MAGIC CREATE OR REPLACE TABLE muestra_estudio_suficiencia_2019 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2019 -- Filtro para NUM_ANO = 2019 
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C'
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC SELECT *
# MAGIC FROM muestra_estudio_suficiencia_2019
# MAGIC limit 10;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla total Año 2019, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_resultados_suficiencia_2019
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_estudio_suficiencia_2019
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_resultados_suficiencia_2019;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2020
# MAGIC CREATE OR REPLACE TABLE muestra_estudio_suficiencia_2020 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2020 -- Filtro para NUM_ANO = 2020 
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C'
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC SELECT *
# MAGIC FROM muestra_estudio_suficiencia_2020
# MAGIC limit 10;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla total Año 2020, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_resultados_suficiencia_2020
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_estudio_suficiencia_2020
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_resultados_suficiencia_2020;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2021
# MAGIC CREATE OR REPLACE TABLE muestra_estudio_suficiencia_2021 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2021 -- Filtro para NUM_ANO = 2021
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C'
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC SELECT *
# MAGIC FROM muestra_estudio_suficiencia_2021
# MAGIC limit 10;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla total Año 2021, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_resultados_suficiencia_2021
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_estudio_suficiencia_2021
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_resultados_suficiencia_2021;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2022
# MAGIC CREATE OR REPLACE TABLE muestra_estudio_suficiencia_2022 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2022 -- Filtro para NUM_ANO = 2022
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C'
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC SELECT *
# MAGIC FROM muestra_estudio_suficiencia_2022
# MAGIC limit 10;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla Año 2022, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_resultados_suficiencia_2022
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_estudio_suficiencia_2022
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_resultados_suficiencia_2022;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Unir las tablas de la muestra años 2018-2022
# MAGIC CREATE OR REPLACE TABLE tabla_destino AS
# MAGIC SELECT * FROM tabla_resultados_suficiencia_2018
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_resultados_suficiencia_2019
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_resultados_suficiencia_2020
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_resultados_suficiencia_2021
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_resultados_suficiencia_2022;
# MAGIC
# MAGIC -- Select data from the table
# MAGIC SELECT *
# MAGIC FROM tabla_destino;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla universo los años 2018-2022, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_universo_resultados_suficiencia
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM temp_suficiencia_unificado_t
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_universo_resultados_suficiencia;

# COMMAND ----------

# MAGIC %md
# MAGIC # Muestra suficiencia filtrodo regimen contributivo 'C' y ESP del estudio de suficiencia

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2018
# MAGIC CREATE OR REPLACE TABLE muestra_eps_suficiencia_contri_2018 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2018 -- Filtro para NUM_ANO = 2018
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC --SELECT *
# MAGIC --FROM muestra_eps_suficiencia_contri_2018
# MAGIC --limit 10;
# MAGIC
# MAGIC
# MAGIC -- Tabla Año 2018, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_eps_suficiencia_contri_2018
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_eps_suficiencia_contri_2018
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_eps_suficiencia_contri_2018;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT STR_IDENTIFICACION, STR_TIPO_ID, COUNT(*) AS conteo
# MAGIC FROM muestra_eps_suficiencia_contri_2018
# MAGIC GROUP BY STR_IDENTIFICACION, STR_TIPO_ID
# MAGIC ;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT COUNT(*) AS total_registros
# MAGIC FROM (
# MAGIC     SELECT STR_IDENTIFICACION, STR_TIPO_ID, COUNT(*) AS conteo
# MAGIC     FROM muestra_eps_suficiencia_contri_2018
# MAGIC     GROUP BY STR_IDENTIFICACION, STR_TIPO_ID
# MAGIC     --HAVING COUNT(*) > 1;
# MAGIC ) subquery;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT STR_IDENTIFICACION, STR_TIPO_ID, COUNT(*) AS conteo
# MAGIC FROM muestra_eps_suficiencia_contri_2018
# MAGIC WHERE STR_IDENTIFICACION = '784420'
# MAGIC GROUP BY STR_IDENTIFICACION, STR_TIPO_ID;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2019
# MAGIC CREATE OR REPLACE TABLE muestra_eps_suficiencia_contri_2019 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2019 -- Filtro para NUM_ANO = 2019
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC --SELECT *
# MAGIC --FROM muestra_eps_suficiencia_contri_2019
# MAGIC --limit 10;
# MAGIC
# MAGIC
# MAGIC -- Tabla Año 2019, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_eps_suficiencia_contri_2019
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_eps_suficiencia_contri_2019
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_eps_suficiencia_contri_2019;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2020
# MAGIC CREATE OR REPLACE TABLE muestra_eps_suficiencia_contri_2020 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2020 -- Filtro para NUM_ANO = 2020
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC --SELECT *
# MAGIC --FROM muestra_eps_suficiencia_contri_2020
# MAGIC --limit 10;
# MAGIC
# MAGIC
# MAGIC -- Tabla Año 2020, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_eps_suficiencia_contri_2020
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_eps_suficiencia_contri_2020
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_eps_suficiencia_contri_2020;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2021
# MAGIC CREATE OR REPLACE TABLE muestra_eps_suficiencia_contri_2021 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2021 -- Filtro para NUM_ANO = 2021
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC --SELECT *
# MAGIC --FROM muestra_eps_suficiencia_contri_2021
# MAGIC --limit 10;
# MAGIC
# MAGIC
# MAGIC -- Tabla Año 2021, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_eps_suficiencia_contri_2021
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_eps_suficiencia_contri_2021
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_eps_suficiencia_contri_2021;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- muestra de 500 mil cédulas únicas año 2022
# MAGIC CREATE OR REPLACE TABLE muestra_eps_suficiencia_contri_2022 AS
# MAGIC SELECT DISTINCT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD
# MAGIC FROM (
# MAGIC   SELECT NUM_ANO, STR_TIPO_ID, STR_IDENTIFICACION, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NUM_VALOR_TOTAL, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, ROW_NUMBER() OVER (PARTITION BY STR_TIPO_ID, STR_IDENTIFICACION ORDER BY STR_TIPO_ID, STR_IDENTIFICACION) AS row_num
# MAGIC   FROM temp_suficiencia_unificado_t
# MAGIC   WHERE NUM_ANO = 2022 -- Filtro para NUM_ANO = 2022
# MAGIC     AND NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC ) subquery
# MAGIC WHERE row_num = 1
# MAGIC ORDER BY RAND()
# MAGIC LIMIT 500000;
# MAGIC
# MAGIC --SELECT *
# MAGIC --FROM muestra_eps_suficiencia_contri_2022
# MAGIC --limit 10;
# MAGIC
# MAGIC
# MAGIC -- Tabla Año 2018, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE tabla_eps_suficiencia_contri_2022
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM muestra_eps_suficiencia_contri_2022
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   tabla_eps_suficiencia_contri_2022;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Unir las tablas de la muestra años 2018_a_2022
# MAGIC CREATE OR REPLACE TABLE atenciones_eps_sufici_contri_2018_a_2022 AS
# MAGIC SELECT * FROM tabla_eps_suficiencia_contri_2018
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_eps_suficiencia_contri_2019
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_eps_suficiencia_contri_2020
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_eps_suficiencia_contri_2021
# MAGIC UNION 
# MAGIC SELECT * FROM tabla_eps_suficiencia_contri_2022;
# MAGIC
# MAGIC -- Select data from the table
# MAGIC SELECT *
# MAGIC FROM atenciones_eps_sufici_contri_2018_a_2022;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Tabla universo los años 2018-2022, NUM_ANO, STR_COD_EPS, DESC_EPS, STR_REGIMEN, STR_COD_ACTIVIDAD,  NOMBRE_ACTIVIDAD, NT_RULES, NT_DENOMINA, DESC_ACTIVIDAD, Suma_total_valor, Frecuencia
# MAGIC CREATE OR REPLACE TABLE base_universo_EPS_reg_contri_suficiencia
# MAGIC AS
# MAGIC SELECT
# MAGIC   TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy') AS Year,
# MAGIC   STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA, 
# MAGIC   SUM(NUM_VALOR_TOTAL) AS Suma_total_valor,
# MAGIC   COUNT(NT_RULES) AS Frecuencia
# MAGIC FROM temp_suficiencia_unificado_t
# MAGIC WHERE NUM_TIPO_REGISTRO IN (2, 5) AND STR_REGIMEN = 'C' AND STR_COD_EPS IN ('EPS002', 'EPS005', 'EPS010', 'EPS012', 'EPS017', 'EPS018', 'EPS037', 'EPS008')
# MAGIC GROUP BY TO_DATE(CAST(NUM_ANO AS STRING), 'yyyy'), STR_COD_EPS, 
# MAGIC   DESC_EPS, 
# MAGIC   STR_REGIMEN, 
# MAGIC   STR_COD_ACTIVIDAD,  
# MAGIC   NOMBRE_ACTIVIDAD, 
# MAGIC   DESC_ACTIVIDAD,
# MAGIC   NT_RULES, 
# MAGIC   NT_DENOMINA;
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   base_universo_EPS_reg_contri_suficiencia;

# COMMAND ----------

import matplotlib.pyplot as plt

# Obtener los datos de la tabla base_universo_EPS_reg_contri_suficiencia
data = spark.sql("SELECT * FROM base_universo_EPS_reg_contri_suficiencia").toPandas()

# Crear el gráfico de barras
plt.figure(figsize=(10, 6))
plt.bar(data['DESC_EPS'], data['Suma_total_valor'])
plt.xlabel('EPS')
plt.ylabel('Suma Total Valor')
plt.title('Suma Total Valor por EPS')
plt.xticks(rotation=90)
plt.show()

# COMMAND ----------

import matplotlib.pyplot as plt

# Obtener los datos de la tabla base_universo_EPS_reg_contri_suficiencia
data = spark.sql("SELECT STR_COD_EPS, Frecuencia FROM base_universo_EPS_reg_contri_suficiencia").toPandas()

# Crear la gráfica de barras
plt.figure(figsize=(10, 6))
plt.bar(data['STR_COD_EPS'], data['Frecuencia'], color='blue')
plt.xlabel('STR_COD_EPS')
plt.ylabel('Frecuencia')
plt.title('Frecuencia por STR_COD_EPS')
plt.xticks(rotation=90)
plt.show()
